## Блокът finally

__Блокът finally__ от конструкцията try-catch-finally се извиква след изпълнението на блокове try или catch.

````
try {
     
    } catch (Exception ex) {
    
    } finally {
     
    }
    
````

Блокът finally се изпълнява, освен в следните случаи:

+ Ако бъде извикано System.exit(0);
+ Ако бъде извикано Runtime.getRuntime().halt(exitStatus);
+ Ако JVM се срине първо;
+ Ако JVM достигне безкраен цикъл (или някакъв друг непрекъсваем, непрекратяващ израз) в try или catch блока;
+ Ако ОС принудително прекрати действието на JVM;
+ Ако хост системата преустанови работа. Например при прекъсване на захранването, хардуерна грешка, или аварийно изключване на ОС;
+ Ако блокът finally е изпълнен от daemon-нишка и всички други нишки (които не са daemon), излязат, преди finally да бъде извикан;